server:
  port: 8081
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: spisok_zadach_service
          uri: http://localhost:8080  # Uri ?????? ??????? ?????
          predicates:
            - Path=/spisokzadach/**  # ??????????????? ???????? ? SpisokZadachController
